### ISSUE TITLE
Build failure with clang-15 due to nested function in profiles/midi/midi.c

### ISSUE THREAD

**Issue by marv** [bluez/bluez#400]
bluez 5.64 fails to build with clang-15.0.1 with the following error:
```
profiles/midi/midi.c:61:75: error: function definition is not allowed here
        void foreach_cb(const struct midi_write_parser *parser, void *user_data) {
                                                                                 ^
profiles/midi/midi.c:78:40: error: use of undeclared identifier 'foreach_cb'
                midi_read_ev(&midi->midi_out, event, foreach_cb, midi);
                                                     ^
2 errors generated.
make[1]: *** [Makefile:9843: profiles/midi/bluetoothd-midi.o] Error 1
```

If it's just a matter of moving the `foreach_cb` function out of the function and making it `static` I'm happy to provide a patch, but I'm not familiar with the code and don't really know the reasons why the nested function was used in the first place and what implications it might have
