### ISSUE TITLE
Autoconf options `--enable-hid` and `--enable-hog` are mutually dependents

### ISSUE THREAD

**Issue by tperale** [bluez/bluez#1228]
The build options `--enable-hid` and `--enable-hog` are mutually dependents. What I mean is that if I try to build bluez with HID support but without HoG the build will fail.

```
> ./configure --enable-hid --disable-hog
> make
...
  CCLD     src/bluetoothd
/usr/bin/ld: profiles/input/bluetoothd-manager.o: in function `input_init':
/home/../bluez-5.79/profiles/input/manager.c:122:(.text.input_init+0x1c8): undefined reference to `input_set_auto_sec'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:6376: src/bluetoothd] Error 1
```

The function `input_set_auto_sec` is part of the hog file. This dependency has been introduced in the commit f2778f5877.

If I try to build bluez without HID but with HoG enabled I get the following error:

```
> ./configure --disable-hid --enable-hog
> make
...
/usr/bin/ld: profiles/input/bluetoothd-hog.o: in function `hog_disconnect':
/home/../bluez-5.79/profiles/input/hog.c:211:(.text.hog_disconnect+0x12): undefined reference to `input_get_userspace_hid'
collect2: error: ld returned 1 exit status
```

The function`input_set_userspace_hid` is part of the hid file. This dependency has been introduced in the commit 1782bfd791.

I'm looking for pointer on how you would like to fix this, I'm willing to send a patch and so far I see multiple options:

1. Warn the user when both options are not enabled/disabled

```diff
diff --git a/configure.ac b/configure.ac
index 1e089aaa7..f38b97301 100644
--- a/configure.ac
+++ b/configure.ac
@@ -199,6 +199,10 @@ AC_ARG_ENABLE(hog, AS_HELP_STRING([--disable-hog],
 		[disable HoG profile]), [enable_hog=${enableval}])
 AM_CONDITIONAL(HOG, test "${enable_hog}" != "no")

+if test "${enable_hid}" != "${enable_hog}"; then
+	AC_MSG_ERROR([--enable-hid and --enable-hog must be either both enabled or both disabled])
+fi
+
 AC_ARG_ENABLE(health, AS_HELP_STRING([--enable-health],
 		[enable health profiles]), [enable_health=${enableval}])
 AM_CONDITIONAL(HEALTH, test "${enable_health}" = "yes")
```

2. Merge the options together
3. Conditionally enable the feature introduced in f2778f5877 & 1782bfd791.

Thank you !

**Comment by Vudentz** [comment]
In theory each plugin shall not have any dependency on each other, so whatever we need as dependency it is either shall come from the core or from shared, which I guess is what you mean by option 3.

**Comment by tperale** [comment]
Thanks, I sent the following https://lore.kernel.org/linux-bluetooth/20250430143610.387300-1-thomas.perale@mind.be/T/#
